FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y nginx && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/share/nginx/html

COPY index.html .
COPY index.css .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

